### ISSUE TITLE
Missing RAM Info

### ISSUE THREAD

**Issue by maxgerhardt** [ch32-rs/defines#1]
Almost none of the chips have RAM declared. For CH32V30x there's a hint in the register descriptions for SRAM size, but that is also not correct for everyh V30x (not all have 256K Flash / 64K RAM)

![grafik](https://user-images.githubusercontent.com/26485477/221367684-67288d6a-a419-493d-abbf-84bd9f53a707.png)

**Comment by septs** [comment]
The repo is now currently frozen, plz check https://github.com/ch32-rs/wchisp/tree/main/devices device definitions
